### ISSUE TITLE
Discussed Dots.Py changes (First ones)

### ISSUE THREAD

**Issue by dpalmer9** [cbattista/OpenPsyc#24]
Heres the list as we discussed:
1. Eliminate Mask between sequential dot arrays
2. Increase Inter-Stimulus Interval and Increase Response Window (crosshair as end of trial)
3. Increase Crosshair Size
4. Blur Mask in Side by Side Presentation
5. Address issue of ratio production
6. Make Reaction Time Variable include Milliseconds
7. Change response coding for Side-by-Side display (which side is larger)
8. Optional: Play with # of blocks- 3 or 4?

**Comment by cbattista** [comment]
cool, next time you upload bugs upload one bug per issue, that way i can keep track of which changes to the codebase fix which bugs, etc etc.  no worries this time though.

**Comment by cbattista** [comment]
fixed in https://github.com/cbattista/OpenPsyc/commit/5669864fda4bfde3104413290b38238e23e5204d

and 

https://github.com/cbattista/OpenPsyc/commit/88c9e49438e413f666eb412267db9bc882d2b541

and 

https://github.com/cbattista/OpenPsyc/commit/d6673d9e62a7e93098713c0555be718a3870a520

and 

https://github.com/cbattista/OpenPsyc/commit/2c5fb4c7fb536c24c7cb78990fddfdc79d44edba

and 

https://github.com/cbattista/OpenPsyc/commit/014630aea984fb5da6f9d7554e07d429b755cb2e
