### ISSUE TITLE
Reaction Time Not Being Properly Coded Dots.py

### ISSUE THREAD

**Issue by dpalmer9** [cbattista/OpenPsyc#27]
Reaction Time`s on average converge around 750-800ms, regardless of participant responce time. Responses coded in sequential during crosshair also give many NA. I noticed in the code you load the time module. Would using the timeit.timer module work, or would changing the definition of the RT period

**Comment by cbattista** [comment]
timeit is used for profiling functions, not for this kind of thing.  this bug is fixed in:

https://github.com/cbattista/OpenPsyc/commit/1c989fef573cd9e7d8f79b2a1d0666405ae965b9

what's been switched is that the dots, mask, and cross are now all contained within the same Presentation object and the appearance of each is determined by checking the master clock.  Reaction time is obtained through a call to Presentation.time_since_go()
