### ISSUE TITLE
Check Accuracy Code for Sequential and Overlap

### ISSUE THREAD

**Issue by dpalmer9** [cbattista/OpenPsyc#29]
I Emailed you already about the Sequential but check the Overlap out as well. I know that one is legitimately tough but I want to play it cautiously. Check to see if it is actually recording it properly or find a new way to code accuracy with both of these types. If both are due to chance then we need new way to define correct response.

**Comment by cbattista** [comment]
yeah overlap and seq are graded the same way and it was confusing me why one worked and the other didn't - this should be easy to fix now :)

**Comment by cbattista** [comment]
so this is a funny one - the bug actually roots back to DotExample.py - the code that 
was generating the arrays was coloring them wrong half the time, so dots.py thought that the large color was yellow when to the user it appeared blue, and vice versa - this only occured half the time though which is why performance seemed at chance and not 0 - so this fix for this is to regenerate  the stimulus library with DotExample.py, which is committed here : 
https://github.com/cbattista/OpenPsyc/commit/a4577824a8f3adf74495764b8b5cfd98d508268d
