### ISSUE TITLE
magnitude-uploaddata problem

### ISSUE THREAD

**Issue by jwlass** [cbattista/OpenPsyc#41]
could not open up the training set after it was made. then everything was outta commission after that...
-tried rerunning uploaddata to make the training set again and it did not work. 
-tried opening pre data but nothign was wrong with it
-tried changing some unverifieds to verified in the pre data but this did not help
-database was already running and worked just before (still tried reloading it but did not work)
-tried running uploadata on another participant who had good pre data and fo which uploadata had previously worked and it did not work at all

**Comment by cbattista** [comment]
This issue was the result of a conflicted DB.  Because the DB runs out of my Dropbox, it occasionally becomes desynchronized.  So, what you have to do in that case is 
1.  Stop the DB.
2.  Go into Dropbox and delete DB files (files ending in .ns) with the words 'conflicted' in them, as well as the mongod.lock file
3.  Restart the DB.

This should solve a conflicted DB issue.
